[tool.pytest.init_options]
addopts = "-q --maxfail=1"
pythonpath = ["src"]

[project]
name = "BeatSaberMapsAI"
version = "0.1.0"
dependencies = [
    "librosa>=0.10",
    "soundfile>=0.12",
    "numpy>=1.26"
]